import torch
res = torch.tensor(1)
print("This is  the code of xiayanheng ,then he will remove from this program!!!")
print("res:",res)
print("夏嘉 is a cool boy")
print("131y74")
print("你干嘛")
print("练习两年半的实习生蔡徐坤")
print("新加了一个成员")
print("最新修改")
print("xiajia-zjut 做的修改")
print("你是真的骚气")
print("xiajia777 commit")
print("你是真的六")
print("你是真的六")
print("你是真的六")
print("xiajia666")
print("练习两年半夏嘉")
